services:
  subtitle-generator:
    build:
      context: .
      args:
        USE_GPU: "false" 
    ports:
      - "8502:8502"
    # IMPORTANT: To enable GPU support, uncomment the lines below.
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]